//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Медицинская_лаборатория.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blood
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public int Barcode { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual BloodService BloodService { get; set; }
    }
}
