//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Медицинская_лаборатория.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Blood = new HashSet<Blood>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Guid { get; set; }
        public string Email { get; set; }
        public int SocialSecNumber { get; set; }
        public string Ein { get; set; }
        public int SocialTypeId { get; set; }
        public string Phone { get; set; }
        public int PassportS { get; set; }
        public int PassportN { get; set; }
        public System.DateTime Birthday { get; set; }
        public int CountryId { get; set; }
        public string InsuranceName { get; set; }
        public string InsuranceAddress { get; set; }
        public int InsuranceInn { get; set; }
        public string IPAddress { get; set; }
        public int InsuranceP { get; set; }
        public int InsuranceBik { get; set; }
        public string Ua { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blood> Blood { get; set; }
        public virtual Country Country { get; set; }
        public virtual SocialType SocialType { get; set; }
    }
}
